### ISSUE TITLE
query regarding degrees of freedom in using ashr

### ISSUE THREAD

**Issue by tanu06** [stephens999/ashr#113]
I am trying to use ashr for FDR correction of my SNP markers after doing GWAS using GRIDLMM. I have a query about using a degree of freedom.

Should my degree of freedom be a vector file with MAF of my SNPs? or is it the number of SNPs going for the FDR test or is it a number of samples I have? Any suggestions or readings will be of great help.

**Comment by stephens999** [comment]
df refers to if you are using a t statistic for your test rather than z scores.
Reading is: M Lu and M Stephens. Empirical Bayes estimation of normal means, accounting for uncertainty in estimated standard errors. arXiv:1901.10679

However, for GWAS the tests are usually pretty close to zscores as sample sizes are very large,
so I woudl think you do not need the df parameter.
