### ISSUE TITLE
ash fails when optmethod==mixIP but REBayes not installed

### ISSUE THREAD

**Issue by stephens999** [stephens999/ashr#19]
this was deliberate, but is causign some unit tests to fail.
Possibly better to issue a warning in this case and default to EM?

**Comment by road2stat** [comment]
I guess they both make sense. The only difference is the balance of logical and "user-friendliness". The former is more logical and less friendly, the other is more friendly but not so logical (although a warning is given).

I justed noticed that the test itself is aimed at testing if `optmethod` switches to EM when given negative probabilities. That is hard to test on Travis since it has no REBayes available at the first place. So maybe not changing the ash logic, just change the test, so it only runs on the machine when REBayes is installed?

**Comment by stephens999** [comment]
good idea. I have tried this.

**Comment by stephens999** [comment]
fixed by 8e4595e
