### ISSUE TITLE
bug with modify.sd0

### ISSUE THREAD

**Issue by stephens999** [stephens999/ashr#46]
@MuzheZeng try this
set.seed(100)
z = rnorm(1000,0,2)
ashr::ash(z1,1,"uniform",gridmult=1.1)

I get

Error in temp[sdzero] = ifelse(A[sdzero] <= M[sdzero] & B[sdzero] >= M[sdzero],  : 
  NAs are not allowed in subscripted assignments

**Comment by MuzheZeng** [comment]
I encounter this before. Now my newest update shows no error in this example. Shall pull request my newest update?--------------------
Muzhe Zeng
University of Chicago, Master of Statistics
Peking University in School of Mathematics(Bachelor)
Double major in Economics, CCER Club(Bachelor)
            在2016年11月12日 10:29，stephens999 写道:@MuzheZeng try this
set.seed(100)
z = rnorm(1000,0,2)
ashr::ash(z1,1,"uniform",gridmult=1.1)
I get
Error in temp[sdzero] = ifelse(A[sdzero] <= M[sdzero] & B[sdzero] >= M[sdzero],  :
NAs are not allowed in subscripted assignments

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/stephens999/ashr","title":"stephens999/ashr","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/stephens999/ashr"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"bug with modify.sd0 (#46)"}],"action":{"name":"View Issue","url":"https://github.com/stephens999/ashr/issues/46"}}}

**Comment by stephens999** [comment]
@MuzheZeng i no longer get an error, but I would like to: a) have a unit test; b) be clear about what the behaviour of the function should be for matrix/vector combinations; c) improve the code if possible.
It seems a) and b) can be done together, as the unit test will help clarify the behaviour.
For example, what should this return:

a=c(0,0)
b=c(1,2)
m = rbind(c(0,2,4),c(0,0,0))
sd = 0
ashr::my_etruncnorm(a,b,m,sd)

?

**Comment by MuzheZeng** [comment]
sure--------------------
Muzhe Zeng
University of Chicago, Master of Statistics
Peking University in School of Mathematics(Bachelor)
Double major in Economics, CCER Club(Bachelor)
            在2016年11月14日 15:56，stephens999 写道:@MuzheZeng i no longer get an error, but I would like to: a) have a unit test; b) be clear about what the behaviour of the function should be for matrix/vector combinations; c) improve the code if possible.
It seems a) and b) can be done together, as the unit test will help clarify the behaviour.
For example, what should this return:

a=c(0,0)
b=c(1,2)
m = rbind(c(0,2,4),c(0,0,0))
sd = 0
ashr::my_etruncnorm(a,b,m,sd)

?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/stephens999/ashr","title":"stephens999/ashr","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/stephens999/ashr"}},"updates":{"snippets":[{"icon":"PERSON","message":"@stephens999 in #46: @MuzheZeng i no longer get an error, but I would like to: a) have a unit test; b) be clear about what the behaviour of the function should be for matrix/vector combinations; c) improve the code if possible.\r\nIt seems a) and b) can be done together, as the unit test will help clarify the behaviour.\r\nFor example, what should this return:\r\n\r\na=c(0,0)\r\nb=c(1,2)\r\nm = rbind(c(0,2,4),c(0,0,0))\r\nsd = 0\r\nashr::my_etruncnorm(a,b,m,sd)\r\n\r\n?"}],"action":{"name":"View Issue","url":"https://github.com/stephens999/ashr/issues/46#issuecomment-260475842"}}}

**Comment by MuzheZeng** [comment]
Professor, my_etruncnorm need to be modified a little bit again for your specific example. Since I did not consider mean being matrix while sd is just a scalar. I've made the change already.

However, I encounter some problem when I try to git push after commit. It said


remote: Permission to stephens999/ashr.git denied to MuzheZeng.

fatal: unable to access 'https://github.com/stephens999/ashr.git/': The requested URL returned error: 403


I thought the procedure should be:

clone from your latest master branch -> make changes -> git add -> git commit -> git push -> pull request on the website


Which step did I make mistake? Thanks!


Bests~

-------------------------
Muzhe Zeng
University of Chicago, Master of Statistics
University of Chicago Booth School of Business, Research Assistant
Peking University, School of Mathematics Science(Bachelor)
Double major in Economics of CCER (Bachelor)
________________________________
发件人: stephens999 [notifications@github.com]
发送时间: 2016年11月14日 15:56
收件人: stephens999/ashr
抄送: Mazon Zeng; Mention
主题: Re: [stephens999/ashr] bug with modify.sd0 (#46)


@MuzheZeng<https://github.com/MuzheZeng> i no longer get an error, but I would like to: a) have a unit test; b) be clear about what the behaviour of the function should be for matrix/vector combinations; c) improve the code if possible.
It seems a) and b) can be done together, as the unit test will help clarify the behaviour.
For example, what should this return:

a=c(0,0)
b=c(1,2)
m = rbind(c(0,2,4),c(0,0,0))
sd = 0
ashr::my_etruncnorm(a,b,m,sd)

?

―

**Comment by stephens999** [comment]
the issue is you are working on a clone of my repo, so you can't push it because you don't have push access to my repo (your cloned repo is linked to my github repo). 

If you had forked my repo instead, that would have created a copy of the repo that was yours, and that you could push to, and then create pull requests of.

It is a common problem I think - and annoying that it isn't entirely obvious how to create a pull request from a cloned repo. But here is an answer: you need to go back and fork my repo, and then
add the changes you have just made on your laptop to that fork (automatically, not by hand!)
Here are instructions:

http://stackoverflow.com/questions/14906187/how-to-submit-a-pull-request-from-a-cloned-repo

**Comment by pcarbo** [comment]
Matthew, branches were designed specifically for the purpose of collaboration, so why don't you work with branches instead of forks?

For example, you could add MuzheZeng as a collaborator, then create a new branch called "muzhe-zeng". If you are worried about collaborators pushing changes to the master branch (which can happen accidentally), you can protect certain branches such as the master branch:

https://help.github.com/articles/about-branch-restrictions

Forks are not meant for two-way collaboration, so I think you will find that collaboration across forks is more complicated.

**Comment by stephens999** [comment]
thanks @pcarbo that would be great

and yes, I think it would be good idea to protect the master branch

**Comment by stephens999** [comment]
@MuzheZeng one of the things you do is make all the arguments the same length.
here is how we should probably do this
(from http://stackoverflow.com/questions/9335099/implementation-of-standard-recycling-rules)

expand_args <- function(...){
  dots <- list(...)
  max_length <- max(sapply(dots, length))
  lapply(dots, rep, length.out = max_length)
}

**Comment by stephens999** [comment]
I think this is mostly addressed by b092794ebe6f29abdfffc130e7dbdd94dddbfb66
